name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Run Rustfmt
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install Cargo Audit
      run: cargo install cargo-audit

    - name: Run Cargo Audit
      run: cargo audit

    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run Tarpaulin
      run: cargo tarpaulin --out Xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        fail_ci_if_error: true